menu:
  - name: Blog
    path: /
    icon: fa fa-home

  - name: Archive
    path: /archives/
    icon: fa fa-folder-open-o

  - name: GitHub
    path: https://github.com/haoliangwu
    icon: fa fa-github-alt

  - name: English
    path: /english/
    icon: fa fa-file

  - name: About
    path: http://www.lagou.com/resume/preview.html
    icon: fa fa-info

favicon: /favicon.ico
logo: /favicon.ico

# Comment
# e.g disqus: seansun
disqus:
duoshuo: littlelyon

# Analytics
# google-analytics:
ga: UA-65933410-1

# Copyright Infomation
startyear: 2016

# Font CDN
#true : use google fonts api, not stable for chinese visitor sometimes, caused by force majeure factor
#false: use useso fonts api instead of google's, great response speed for chinese visitor
googlefonts: false
